name: New event
description: Add an event
body:
    - type: input
      id: date
      validations:
          required: true
      attributes:
          label: Time and date
          placeholder: "Time and date as: (?)"

    - type: input
      id: location
      validations:
          required: true
      attributes:
          label: Location
          placeholder: "Address or name of the place (?)"

    - type: input
      id: organisator
      validations:
          required: true
      attributes:
          label: Organisator
          placeholder: Organisator

    - type: textarea
      id: description
      validations:
          required: true
      attributes:
          label: Description
          placeholder: Description

    - type: input
      id: joining_link
      validations:
          required: true
      attributes:
          label: Joining link
          placeholder: Joining link
