name: New meetup
description: Add a meetup
labels: [meetup]
body:
  - type: input
    id: title
    validations:
      required: true
    attributes:
      label: Meetup title
      placeholder: "Let's all learn JavaScript"

  - type: input
    id: signupLink
    validations:
      required: true
    attributes:
      label: Signup link for meetup

  - type: input
    id: organizer
    validations:
      required: true
    attributes:
      label: Organizer

  - type: input
    id: organizerLink
    validations:
      required: true
    attributes:
      label: Organizer link

  - type: input
    id: date
    validations:
      required: true
    attributes:
      label: Date
      placeholder: Date as yyyy-MM-dd

  - type: input
    id: time
    validations:
      required: true
    attributes:
      label: Time
      placeholder: Time as HH:mm

  - type: input
    id: location
    validations:
      required: true
    attributes:
      label: Street address

  - type: input
    id: locationLink
    validations:
      required: true
    attributes:
      label: Maps link for address

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
