name: "new-meetup-action"
description: "New meetup action"
author: "oulu-dev-meetups"
inputs:
    issue_title:
        required: true
        description: "Issue title"
    issue_body:
        required: true
        description: "Issue body"
    issue_number:
        required: true
        description: "Issue number"
    meetup_folder:
        required: true
        description: "New meetup files are added here"

runs:
    using: "node16"
    main: "lib/index.js"
