name: "new-meetup-action"
description: "New meetup action"
author: "oulu-dev-meetups"
inputs:
    meetup_folder:
        required: true
        description: "New meetup files are added here"
    issue_title:
        required: true
        description: "Issue title"
        default: ${{ github.event.issue.title }}
    issue_body:
        required: true
        description: "Issue body"
        default: ${{ github.event.issue.body }}
    issue_number:
        required: true
        description: "Issue number"
        default: ${{ github.event.issue.number }}
    github_token:
        required: true
        description: "Github token"
        default: ${{ github.token }}

runs:
    using: "composite"
    steps:
        - run: npm i -g pnpm
          shell: bash

        - run: pnpm i
          shell: bash
          working-directory: .github/workflows/new-meetup

        - run: pnpm start
          shell: bash
          working-directory: .github/workflows/new-meetup
