name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manual trigger

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-and-cache

      - run: |
          pnpm install
          pnpm build
        env:
          PUBLIC_API_BASE_URL: https://api.admin-e68.workers.dev/

      - name: Deploy
        working-directory: ./packages/site
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          pnpm run deploy -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
