name: New meetup

permissions:
    contents: write
    pull-requests: write

on:
    issues:
        types: [opened]

jobs:
    new-meetup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run new meetup action
              uses: ./.github/workflows/new-meetup
              id: new-meetup-action
              with:
                  issue_title: ${{ github.event.issue.title }}
                  issue_body: ${{ github.event.issue.body }}
                  issue_number: ${{ github.event.issue.number }}
                  meetup_folder: "src/content/meetups"

            - name: Create pull request
              uses: peter-evans/create-pull-request@v5
              with:
                  branch: ${{ steps.new-meetup-action.outputs.branch_name }}
                  title: ${{ steps.new-meetup-action.outputs.pull_request_title }}
                  body: ${{ steps.new-meetup-action.outputs.pull_request_body }}
