name: New event

permissions:
    contents: write
    pull-requests: write

on:
    issues:
        types: [opened]

jobs:
    new-event:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Parse issue body
              uses: stefanbuck/github-issue-parser@v3
              id: issue-parser
              with:
                  template-path: .github/ISSUE_TEMPLATE/new-event.yml

            - name: Parse issue body description
              id: issue-body-desc
              run: echo ISSUE_BODY_DESC=$(echo "${{ github.event.issue.body }}" | perl -0777 -nE 'print $1 if /### Description\s*\n\s*(.*)/s;') >> $GITHUB_OUTPUT

            - name: Create new event file
              env:
                  DATE: ${{ steps.issue-parser.outputs.issueparser_date }}
                  LOCATION: ${{ steps.issue-parser.outputs.issueparser_location }}
                  LOCATION_GOOGLE_MAPS: ${{ steps.issue-parser.outputs.issueparser_location_google_maps }}
                  ORGANISER: ${{ steps.issue-parser.outputs.issueparser_organiser }}
                  ORGANISER_LINK: ${{ steps.issue-parser.outputs.issueparser_organiser_link }}
                  JOINING_LINK: ${{ steps.issue-parser.outputs.issueparser_joining_link }}
                  DESCRIPTION: ${{ steps.issue-body-desc.ISSUE_BODY_DESC }}
              run: |
                  cat <<EOF > new_event.md

                  ---
                  date: "$DATE"
                  location: "$LOCATION"
                  location_google_maps: "$LOCATION_GOOGLE_MAPS"
                  organiser: "$ORGANISER"
                  organiser_link: "$ORGANISER_LINK"
                  joining_link: "$JOINING_LINK"
                  ---

                  $DESCRIPTION
                  EOF

            - name: Create pull request
              uses: peter-evans/create-pull-request@v5
