name: New event

on:
    issues:
        types: [opened]

jobs:
    new-event:
        runs-on: ubuntu-latest

        steps:
            - name: View the github context
              run: echo "$GITHUB_CONTEXT"
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
