name: New meetup

permissions:
    contents: write
    pull-requests: write
    issues: write

on:
    issues:
        types: [opened]

jobs:
    new-meetup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run new meetup action
              uses: ./.github/workflows/new-meetup
              id: new_meetup_action
              with:
                  meetup_folder: "src/content/meetups"

            - name: Create pull request
              uses: peter-evans/create-pull-request@v5
              id: create_pr
              with:
                  branch: ${{ steps.new_meetup_action.outputs.branch_name }}
                  title: ${{ steps.new_meetup_action.outputs.pull_request_title }}
                  body: ${{ steps.new_meetup_action.outputs.pull_request_body }}

            - name: Update comment
              uses: ./.github/workflows/post-create-pr
              with:
                  pull_request_number: ${{ steps.create_pr.outputs.pull-request-number }}
                  comment_id: ${{ steps.new_meetup_action.outputs.comment_id }}
