name: New meetup

permissions:
    contents: write
    pull-requests: write

on:
    issues:
        types: [opened]

jobs:
    new-meetup:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run new meetup action
              uses: ./.github/workflows/new-meetup
              id: new-meetup-action
              with:
                  issue_title: ${{ github.event.issue.title }}
                  issue_body: ${{ github.event.issue.body }}
                  issue_number: ${{ github.event.issue.number }}

            # - name: Parse issue body
            #   uses: stefanbuck/github-issue-parser@v3
            #   id: issue-parser
            #   with:
            #       template-path: .github/ISSUE_TEMPLATE/new-meetup.yml

            # - name: Create new meetup file
            #   env:
            #       DATE: ${{ steps.issue-parser.outputs.issueparser_date }}
            #       LOCATION: ${{ steps.issue-parser.outputs.issueparser_location }}
            #       LOCATION_GOOGLE_MAPS: ${{ steps.issue-parser.outputs.issueparser_location_google_maps }}
            #       ORGANISER: ${{ steps.issue-parser.outputs.issueparser_organiser }}
            #       ORGANISER_LINK: ${{ steps.issue-parser.outputs.issueparser_organiser_link }}
            #       JOINING_LINK: ${{ steps.issue-parser.outputs.issueparser_joining_link }}
            #   run: |
            #       DESCRIPTION=$(echo "${{ github.event.issue.body }}" | perl -0777 -nE 'print $1 if /### Description\s*(.*)/s;')
            #       cat <<EOF > new_meetup.md

            #       ---
            #       date: "$DATE"
            #       location: "$LOCATION"
            #       location_google_maps: "$LOCATION_GOOGLE_MAPS"
            #       organiser: "$ORGANISER"
            #       organiser_link: "$ORGANISER_LINK"
            #       joining_link: "$JOINING_LINK"
            #       ---

            #       $DESCRIPTION
            #       EOF

            # - name: Get details
            #   run: |
            #       echo "BRANCH_NAME=new-meetup-" >> $GITHUB_OUTPUT

            - name: Create pull request
              uses: peter-evans/create-pull-request@v5
              with:
                  branch: ${{ steps.new-meetup-action.outputs.branch_name }}
                  title: ${{ steps.new-meetup-action.outputs.pull_request_title }}
                  body: ${{ steps.new-meetup-action.outputs.pull_request_body }}
