name: New meetup

permissions:
    contents: write
    pull-requests: write
    issues: write

on:
    issues:
        types: [opened]

jobs:
    new-meetup:
        runs-on: ubuntu-latest

        steps:
            - name: Check if should run
              id: should-run
              if: "contains( github.event.issue.labels.*.name, 'meetup' )"
              run: echo "hi"

            - name: Checkout
              needs: [should-run]
              uses: actions/checkout@v3

            - name: Create new meetup
              needs: [should-run]
              id: new_meetup
              run: |
                  cd actions/new-meetup && \
                  npm i -g pnpm && \
                  pnpm i && \
                  pnpm start
              env:
                  MEETUP_FOLDER: "../../../src/content/meetups"
                  ISSUE_TITLE: ${{ github.event.issue.title }}
                  ISSUE_BODY: ${{ github.event.issue.body }}
                  ISSUE_NUMBER: ${{ github.event.issue.number }}
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Create pull request
              needs: [should-run]
              uses: peter-evans/create-pull-request@v5
              id: create_pr
              with:
                  branch: ${{ steps.new_meetup.outputs.branch_name }}
                  title: ${{ steps.new_meetup.outputs.pull_request_title }}
                  body: ${{ steps.new_meetup.outputs.pull_request_body }}

            - name: Update comment
              needs: [should-run]
              run: |
                  cd actions/post-create-pr && \
                  npm i -g pnpm && \
                  pnpm i && \
                  pnpm start
              env:
                  PULL_REQUEST_NUMBER: ${{ steps.create_pr.outputs.pull-request-number }}
                  COMMENT_ID: ${{ steps.new_meetup.outputs.comment_id }}
                  GITHUB_TOKEN: ${{ github.token }}
